# Generated by Django 2.0.5 on 2018-05-31 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtn_id', models.IntegerField(default=1)),
                ('login_user', models.CharField(max_length=25)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=25)),
                ('question', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'Java script'), ('shell', 'Shell'), ('git', 'Git')], max_length=10)),
            ],
        ),
    ]
