# Generated by Django 2.0.5 on 2018-06-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='login_user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='login_user',
        ),
    ]
