# Generated by Django 2.0.5 on 2018-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180601_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='login_user',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='question',
            name='login_user',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
