# Generated by Django 2.0.5 on 2018-06-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_gist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gist',
        ),
    ]
